config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # verb "path", to: "controller_name#action"

  # List all lost pets
  get "pets", to: "pets#index"

  # Create a post about a lost pet
  get "pets/new", to: "pets#new", as: "new_pet"

  post "pets", to: "pets#create"

  # Show information on one specific pet
  get "pets/:id", to: "pets#show", as: "pet"

  # Update a given pet
  get "pets/:id/edit", to: "pets#edit", as: "edit_pet"
  patch "pets/:id", to: "pets#update"

  # Remove a post about a pet
  delete "pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["Guinea Pig", "Dog", "Cat", "Ferret", "Rabbit", "Parrot"]
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    # WHITELISTING
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<h1>Pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <%= link_to "#{pet.name} (#{pet.species})", pet_path(pet) %>
    </li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p>Species: <%= @pet.species %></p>
<p>Address: <%= @pet.address %></p>
<p>Found on: <%= @pet.found_on %></p>

<%= link_to "Edit post about #{@pet.name}", edit_pet_path(@pet), class: "btn btn-info" %>

<%= link_to "Destroy post about #{@pet.name}", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>

<%= link_to "See all lost pets", pets_path, class: "btn btn-primary" %>